export const APIConstant = {
  Auth: {
    login: 'Clients/clientLogin',
    register: 'Clients/Registerclient',
    verifyOTP: 'Account/VerifyOTP',
    sendOTP: 'Account/SendOTP',
  },
  contactUs: 'Account/SendEmail',
  prescriptionForm: 'Prescriptions',
  complaintForm: 'Complaints',
  complainTypes: 'Lookups?tableName=ComplaintsTypes',
  nationality: 'Lookups?tableName=Nationalities',
  Clients: 'Clients',
  Coaches: 'Coaches',
  Gyms: 'Gyms',
  Kitchens: 'Kitchens',
  Addresses: 'Addresses',
  Tests: 'Tests',
  Plans: 'Plans',
  FrequentlyQuestions: 'FrequentlyQuestions',
  Doctors: 'Doctors',
  Orders: 'Orders',
  Clinics: 'Clinics',
  Recommendations: 'Recommendations',
  HomeRecommendations:'HomeRecommendations',
  Reviews:"Reviews",
};
